version: '3.8'

services:
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - virtuoso_volume:/data
    ports:
      - "8890:8890"

  face-hunter:
    build: .

volumes:
  virtuoso_volume:
    driver: local